- name: Create an EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch instance
      ec2:
         key_name: Ansible
         group: grafana_group
         instance_type: t2.micro
         image: ami-06e55c17bfd9792fc
         wait: true
         region: us-east-1
         # aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
         # aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2
    - name: Get theh Ip address
      debug: var=ec2.instances[0].public_dns_name

    - name: add host to group 'just_created' with variable foo=42
      add_host:
        name: "{{ ec2.instances[0].public_dns_name }}"
        groups: ec2_hosts
        ansible_host: "{{ ec2.instances[0].public_dns_name }}"
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: ~/ansible.pem
  
    - name: Wait for a while
      pause: seconds=60


- name: Install stuff into ec2 hosts
  hosts: ec2_hosts
  become: yes
  tasks:
  - shell: shell.sh