- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
  roles:
    - nginx
    - prometheus
    - node_exporter
    - grafana
