---
- name: Create an EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch instance
      ec2:
         key_name: Ansible
         group: grafana_group
         instance_type: t2.micro
         image: ami-0dba2cb6798deb6d8
         wait: true
         region: us-east-1
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2
    - name: Get theh Ip address
      debug: var=ec2.instances[0].public_dns_name

    - name: add host to group 'just_created' with variable foo=42
      add_host:
        name: "{{ ec2.instances[0].public_dns_name }}"
        groups: ec2_hosts
        ansible_host: "{{ ec2.instances[0].public_dns_name }}"
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: ~/Ansible.pem
  
    - name: Wait for a while
      pause: seconds=60

- name: run roles on remote box
  hosts: ec2-hosts
  become: true
  roles:
    - ubuntu_update
    - github
    - nginx
    - prometheus
    - node_exporter
    - grafana
