- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Download nginx
      apt:  
        pkg:
        -  nginx
    - name: Create prometheus user
      user:
        name: prometheus
        state: present
        shell: /bin/false
        system: no 
        createhome: no
      become_user: root
    - name: Create node_exporter user
      user:
        name: node_exporter
        state: present
        shell: /bin/false
        system: no 
        createhome: no
      become_user: root
    - name: Create directory
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      with_items: 
        - /etc/prometheus
        - /var/lib/prometheus
    - name: Unarchive a file that needs to be downloaded
      unarchive:
        src: https://github.com/prometheus/prometheus/releases/download/v2.21.0/prometheus-2.21.0.linux-amd64.tar.gz
        dest: /home/ubuntu
        remote_src: yes
    - name: Copy file
      copy:
        src: /home/ubuntu/prometheus-2.21.0.linux-amd64/prometheus
        dest: /usr/local/bin/
    - name: Copy file
      copy:
        src: /home/ubuntu/prometheus-2.21.0.linux-amd64/promtool
        dest: /usr/local/bin/
    - name: Change file permission
      file:
        path: /usr/local/bin/prometheus
        owner: prometheus
        group: prometheus
    - name: Change file permission
      file:
        path: /usr/local/bin/promtool
        owner: prometheus
        group: prometheus
    - name: Copy file
      copy:
        src: /home/ubuntu/prometheus-2.21.0.linux-amd64/consoles
        dest: /etc/prometheus
    - name: Copy file
      copy:
        src: /home/ubuntu/prometheus-2.21.0.linux-amd64/console_libraries
        dest: /etc/prometheus
    - name: Change file permission
      file:
        path: /etc/prometheus/consoles
        owner: prometheus
        group: prometheus
    - name: Change file permission
      file:
        path: /etc/prometheus/console_libraries
        owner: prometheus
        group: prometheus
    - name: Delete unwanted files
      file:
        state: absent
        path: /home/ubuntu/prometheus-2.21.0.linux-amd64
    - name: Delete unwanted files
      file:
        state: absent
        path: /home/ubuntu/prometheus-2.21.0.linux-amd64.tar.gz
    - name: Copy file
      copy:
        src: /home/ubuntu/grafana/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
    - name: Change file permission
      file:
        path: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
    - name: run shell script
      shell:
        sudo -u prometheus /usr/local/bin/prometheus \
        --config.file /etc/prometheus/prometheus.yml \
        --storage.tsdb.path /var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries &
    - name: Copy file
      copy:
        src: /home/ubuntu/grafana/prometheus.service
        dest: /etc/systemd/system/prometheus.service
    - name: Start prometheus
      systemd:
        state: started
        name: prometheus
        daemon_reload: yes
        enabled: yes
    - name: Unarchive a file that needs to be downloaded
      unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
        dest: /home/ubuntu
        remote_src: yes
    - name: Copy file
      copy:
        src: /home/ubuntu/node_exporter-1.0.1.linux-amd64/node_exporter
        dest: /usr/local/bin/
    - name: Change file permission
      file:
        path: /usr/local/bin/node_exporter
        owner: node_exporter
        group: node_exporter
    - name: Delete unwanted files
      file:
        state: absent
        path: /home/ubuntu/node_exporter-1.0.1.linux-amd64.tar.gz
    - name: Delete unwanted files
      file:
        state: absent
        path: /home/ubuntu/node_exporter-1.0.1.linux-amd64
    - name: Copy file
      copy:
        src: /home/ubuntu/grafana/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
    - name: Start node_exporter
      systemd:
        state: started
        name: node_exporter
        daemon_reload: yes
        enabled: yes
    - name: Copy file
      copy:
        src: /home/ubuntu/grafana/prometheus2.yml
        dest: /etc/prometheus/prometheus.yml
    - name: Restart prometheus
      systemd:
        name: prometheus
        state: restarted
    - name: Download adduser libfontconfig
      apt: 
        pkg:
        - adduser
        - libfontconfig   
    - name: Download grafana  
      unarchive:
        src: https://dl.grafana.com/oss/release/grafana_7.2.0_amd64.deb
        dest: /home/ubuntu
        remote_src: yes
    - name: Start grafana
      systemd:
        state: started
        name: grafana-server
        daemon_reload: yes
        enabled: yes
